version: '3'
services:
  frontend:
    image: franarnaudo/fisio-app:fisio-app-fe-axis
    ports:
      - "3001:80"
    environment:
      - VITE_API_URL=http://localhost:8080
    restart: always

  backend:
    image: franarnaudo/fisio-app:fisio-app-be-axis
    ports:
      - "8080:3000"
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Fran24
      - POSTGRES_DB=fisio-app
    restart: always

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Fran24
      POSTGRES_DB: fisio-app
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
    driver: local
