version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Fran24
      POSTGRES_DB: fisio-app
    ports:
      - '5432:5432'

  backend:
    build: .
    depends_on:
      - db
    environment:
      # Use the service name "db" as the database host
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Fran24
      POSTGRES_DB: fisio-app
    ports:
      - '3000:3000'

  frontend:
    build: ../fisio-app-fe
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://127.0.0.1:3000
    ports:
      - '3001:3001'

